#!/bin/bash
ITERATION=7
APP_INDEX=1
CONSUMER_KEY=
CONSUMER_SECRET=
OAUTH_TOKEN=
OAUTH_SECRET=
heroku config:add BOT_NAME=happiness2_u_$ITERATION BOT_TWITTER_CONSUMER_KEY=$CONSUMER_KEY BOT_TWITTER_CONSUMER_SECRET=$CONSUMER_SECRET BOT_TWITTER_OAUTH_TOKEN=$OAUTH_TOKEN BOT_TWITTER_OAUTH_TOKEN_SECRET=$OAUTH_SECRET ENV=production --app hb$APP_INDEX
