#!/bin/bash
ITERATION=9
APP_INDEX=3
CONSUMER_KEY=<key>
CONSUMER_SECRET=<secret>
OAUTH_TOKEN=<token>
OAUTH_SECRET=<secret>
heroku config:add BOT_NAME=happiness2_u_$ITERATION BOT_TWITTER_CONSUMER_KEY=$CONSUMER_KEY BOT_TWITTER_CONSUMER_SECRET=$CONSUMER_SECRET BOT_TWITTER_OAUTH_TOKEN=$OAUTH_TOKEN BOT_TWITTER_OAUTH_TOKEN_SECRET=$OAUTH_SECRET ENV=production --app hb$APP_INDEX
